spring:
  application:
    name: BinaryTreeRests

  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql

  datasource:
    url: jdbc:postgresql://binary-db:5432/BinaryTree
    username: postgres
    password: postgres


server:
  port: 8081

security:
  jwt:
    secret-key: c0f95beb258890a8a4ed4a19b77cda051aea28113825dac5cdb35e9a4e88a3c9
    expiration-time: 3600000